"""
DataCenterEnv — Carbon-aware scheduler using real CloudSim task traces
and real carbon intensity data.

Reads:
  - tasks.csv   : generated by CloudSim Plus WorkloadGenerator.java
  - carbon.csv  : generated by fetch_carbon_data.py (India grid data)

Action space  : Discrete(N_SERVERS + 1)
                  0..N_SERVERS-1 → assign current head-of-queue task to server i
                  N_SERVERS      → defer task

Observation   : Box of shape (OBS_DIM,) containing
                  • per-server CPU utilisation     (20 values, [0,1])
                  • per-server memory utilisation  (20 values, [0,1])
                  • per-server active task count   (20 values, normalised)
                  • head-of-queue task features    (4 values)
                  • queue length                   (1 value, normalised)
                  • current carbon intensity       (1 value, normalised)
                  • current timestep               (1 value, normalised)

Reward        : -(0.5 * CO2 + 0.3 * energy + 0.2 * sla_penalty)
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces

# ──────────────────────────────────────────────────────────────────────────────
# Paths — tasks.csv and carbon.csv must be in the same folder as simulator.py
# ──────────────────────────────────────────────────────────────────────────────

_HERE        = os.path.dirname(os.path.abspath(__file__))
TASKS_CSV    = os.path.join(_HERE, "tasks.csv")
CARBON_CSV   = os.path.join(_HERE, "carbon.csv")

# ──────────────────────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────────────────────

N_SERVERS        = 20
MAX_STEPS        = 200
MAX_QUEUE        = 50
TASK_ARRIVAL_PROB = 0.7   # probability a new CloudSim task is pulled each step

# Carbon intensity fallback parameters (used only if carbon.csv is missing)
CARBON_BASE      = 700.0  # India grid baseline gCO2/kWh
CARBON_AMPLITUDE = 80.0
CARBON_PERIOD    = 48
CARBON_NOISE_STD = 25.0

# ──────────────────────────────────────────────────────────────────────────────
# Server fleet (EC2-like heterogeneous)
# ──────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ServerSpec:
    name: str
    cpu_capacity: float
    mem_capacity: float
    idle_power: float
    peak_power: float

SERVER_TYPES = [
    ServerSpec("micro",  1.0,  1.0,  20,  60),
    ServerSpec("small",  2.0,  4.0,  40,  120),
    ServerSpec("medium", 4.0,  8.0,  80,  220),
    ServerSpec("large",  8.0,  16.0, 150, 400),
]

_TYPE_COUNTS = [5, 5, 6, 4]  # 5 micro, 5 small, 6 medium, 4 large
FLEET: list[ServerSpec] = []
for spec, count in zip(SERVER_TYPES, _TYPE_COUNTS):
    FLEET.extend([spec] * count)

assert len(FLEET) == N_SERVERS

# ──────────────────────────────────────────────────────────────────────────────
# Task dataclass
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class Task:
    task_id:    int
    cpu_demand: float
    mem_demand: float
    duration:   int
    deadline:   int
    remaining:  int = 0
    server_idx: int = -1

    def __post_init__(self):
        self.remaining = self.duration

# ──────────────────────────────────────────────────────────────────────────────
# Data loaders
# ──────────────────────────────────────────────────────────────────────────────

def _load_tasks() -> list[dict]:
    """
    Load CloudSim tasks from tasks.csv.
    Falls back to synthetic tasks if file not found.
    """
    if not os.path.exists(TASKS_CSV):
        print(f"[simulator] WARNING: {TASKS_CSV} not found — using synthetic tasks.")
        return _synthetic_tasks(1000)

    df = pd.read_csv(TASKS_CSV)
    print(f"[simulator] Loaded {len(df)} tasks from {TASKS_CSV}")

    # Normalise column names (CloudSim export uses these names)
    required = {"task_id", "cpu_demand", "memory_demand", "deadline", "arrival_time"}
    missing  = required - set(df.columns)
    if missing:
        print(f"[simulator] WARNING: Missing columns {missing} — using synthetic tasks.")
        return _synthetic_tasks(1000)

    records = []
    for _, row in df.iterrows():
        # Normalise cpu_demand to [0.05, 1.5] range matching ServerSpec capacities
        cpu = float(np.clip(row["cpu_demand"] / 8.0, 0.05, 1.5))
        mem = float(np.clip(row["memory_demand"] / 1024.0, 0.05, 2.0))
        dur = int(np.clip(row.get("length", 5000) / 1000, 2, 15))
        records.append({
            "task_id":      int(row["task_id"]),
            "cpu_demand":   cpu,
            "mem_demand":   mem,
            "duration":     dur,
            "arrival_step": int(row["arrival_time"]) % MAX_STEPS,
            "deadline_offset": int(np.clip(row["deadline"] - row["arrival_time"], 5, 50)),
        })
    return records


def _synthetic_tasks(n: int) -> list[dict]:
    """Fallback synthetic task list."""
    rng = np.random.default_rng(0)
    records = []
    t = 0.0
    for i in range(n):
        t += rng.exponential(3.6)
        dur = int(rng.integers(2, 15))
        records.append({
            "task_id":         i,
            "cpu_demand":      float(rng.uniform(0.05, 1.5)),
            "mem_demand":      float(rng.uniform(0.05, 2.0)),
            "duration":        dur,
            "arrival_step":    int(t) % MAX_STEPS,
            "deadline_offset": int(rng.integers(5, 50)),
        })
    return records


def _load_carbon_profile() -> np.ndarray:
    """
    Load real carbon intensity from carbon.csv (generated by fetch_carbon_data.py).
    Falls back to sine-wave synthetic profile if file is missing.
    """
    if not os.path.exists(CARBON_CSV):
        print(f"[simulator] WARNING: {CARBON_CSV} not found — using synthetic carbon.")
        return _synthetic_carbon(MAX_STEPS * 10)

    df = pd.read_csv(CARBON_CSV)
    if "carbon_intensity" not in df.columns:
        print("[simulator] WARNING: carbon.csv missing 'carbon_intensity' column.")
        return _synthetic_carbon(MAX_STEPS * 10)

    profile = df["carbon_intensity"].values.astype(np.float32)
    print(f"[simulator] Loaded {len(profile)} carbon intensity values from {CARBON_CSV}")
    return profile


def _synthetic_carbon(n: int) -> np.ndarray:
    t = np.arange(n, dtype=np.float32)
    sine  = CARBON_AMPLITUDE * np.sin(2 * np.pi * t / CARBON_PERIOD)
    noise = np.random.default_rng(1).normal(0, CARBON_NOISE_STD, n).astype(np.float32)
    return np.clip(CARBON_BASE + sine + noise, 50, 900).astype(np.float32)

# ──────────────────────────────────────────────────────────────────────────────
# Environment
# ──────────────────────────────────────────────────────────────────────────────

class DataCenterEnv(gym.Env):
    """
    Carbon-aware heterogeneous data-centre scheduler.
    Uses real CloudSim Plus task traces and real India grid carbon data.
    """

    metadata = {"render_modes": ["human", "ansi"], "render_fps": 4}
    OBS_DIM  = 67   # same layout as original simulator.py

    # ── class-level data (loaded once) ────────────────────────────────────────
    _ALL_TASKS:      list[dict]    = []
    _CARBON_PROFILE: np.ndarray    = np.array([])
    _DATA_LOADED:    bool          = False

    @classmethod
    def _ensure_data(cls):
        if not cls._DATA_LOADED:
            cls._ALL_TASKS      = _load_tasks()
            cls._CARBON_PROFILE = _load_carbon_profile()
            cls._DATA_LOADED    = True

    def __init__(self, max_steps: int = MAX_STEPS, seed: int | None = None):
        super().__init__()
        DataCenterEnv._ensure_data()

        self.max_steps  = max_steps
        self._base_seed = seed

        self.action_space      = spaces.Discrete(N_SERVERS + 1)
        self.observation_space = spaces.Box(
            low=0.0, high=1.0, shape=(self.OBS_DIM,), dtype=np.float32
        )

        self._rng: np.random.Generator = np.random.default_rng(seed)
        self._reset_state()

    def _reset_state(self):
        self._step          = 0
        self._task_counter  = 0
        self._cpu_used      = np.zeros(N_SERVERS)
        self._mem_used      = np.zeros(N_SERVERS)
        self._active_tasks  = [[] for _ in range(N_SERVERS)]
        self._queue: list[Task] = []
        self._total_co2     = 0.0
        self._total_energy  = 0.0
        self._total_sla     = 0.0
        self._completed     = 0
        self._missed_sla    = 0

        # Shuffle task list for variety each episode
        self._episode_tasks = self._rng.permutation(
            len(DataCenterEnv._ALL_TASKS)
        ).tolist()
        self._task_ptr = 0   # index into _episode_tasks

    # ── carbon intensity from real profile ────────────────────────────────────

    def _carbon_intensity(self, t: int) -> float:
        profile = DataCenterEnv._CARBON_PROFILE
        if len(profile) == 0:
            return CARBON_BASE
        idx = t % len(profile)
        return float(profile[idx])

    # ── task spawning from CloudSim trace ─────────────────────────────────────

    def _spawn_task(self) -> Task | None:
        """Pull next CloudSim task with arrival probability."""
        if self._rng.random() > TASK_ARRIVAL_PROB:
            return None
        if self._task_ptr >= len(self._episode_tasks):
            self._task_ptr = 0   # wrap around

        raw_idx  = self._episode_tasks[self._task_ptr]
        self._task_ptr += 1
        raw      = DataCenterEnv._ALL_TASKS[raw_idx]

        self._task_counter += 1
        deadline = self._step + raw["deadline_offset"]

        return Task(
            task_id    = self._task_counter,
            cpu_demand = raw["cpu_demand"],
            mem_demand = raw["mem_demand"],
            duration   = raw["duration"],
            deadline   = deadline,
        )

    # ── server helpers (unchanged from original) ──────────────────────────────

    def _server_power(self, idx: int) -> float:
        spec     = FLEET[idx]
        cpu_util = self._cpu_used[idx] / spec.cpu_capacity
        mem_util = self._mem_used[idx] / spec.mem_capacity
        util     = float(np.clip((cpu_util + mem_util) / 2.0, 0.0, 1.0))
        return spec.idle_power + util * (spec.peak_power - spec.idle_power)

    def _can_fit(self, server_idx: int, task: Task) -> bool:
        spec = FLEET[server_idx]
        return (
            self._cpu_used[server_idx] + task.cpu_demand <= spec.cpu_capacity
            and self._mem_used[server_idx] + task.mem_demand <= spec.mem_capacity
        )

    def _assign_task(self, task: Task, server_idx: int) -> None:
        task.server_idx = server_idx
        task.remaining  = task.duration
        self._cpu_used[server_idx] += task.cpu_demand
        self._mem_used[server_idx] += task.mem_demand
        self._active_tasks[server_idx].append(task)

    def _advance_tasks(self) -> int:
        sla_hits = 0
        for s_idx in range(N_SERVERS):
            still_running = []
            for task in self._active_tasks[s_idx]:
                task.remaining -= 1
                if task.remaining <= 0:
                    self._cpu_used[s_idx] -= task.cpu_demand
                    self._mem_used[s_idx] -= task.mem_demand
                    self._completed += 1
                    if self._step > task.deadline:
                        sla_hits += 1
                        self._missed_sla += 1
                else:
                    still_running.append(task)
            self._active_tasks[s_idx] = still_running
        return sla_hits

    def _expire_queued_tasks(self) -> int:
        expired = [t for t in self._queue if self._step > t.deadline]
        for t in expired:
            self._missed_sla += 1
        self._queue = [t for t in self._queue if self._step <= t.deadline]
        return len(expired)

    # ── observation ───────────────────────────────────────────────────────────

    def _build_obs(self) -> np.ndarray:
        obs = np.zeros(self.OBS_DIM, dtype=np.float32)
        for i, spec in enumerate(FLEET):
            obs[i]      = float(np.clip(self._cpu_used[i] / spec.cpu_capacity, 0, 1))
            obs[20 + i] = float(np.clip(self._mem_used[i] / spec.mem_capacity, 0, 1))
            obs[40 + i] = float(np.clip(len(self._active_tasks[i]) / 10.0, 0, 1))

        if self._queue:
            hq      = self._queue[0]
            max_cpu = max(s.cpu_capacity for s in FLEET)
            max_mem = max(s.mem_capacity for s in FLEET)
            obs[60] = float(np.clip(hq.cpu_demand / max_cpu, 0, 1))
            obs[61] = float(np.clip(hq.mem_demand / max_mem, 0, 1))
            total_slack     = max(hq.deadline - (self._step - hq.duration), 1)
            remaining_slack = max(hq.deadline - self._step, 0)
            obs[62] = float(np.clip(1.0 - remaining_slack / total_slack, 0, 1))
            obs[63] = float(np.clip(hq.duration / 15.0, 0, 1))

        obs[64] = float(np.clip(len(self._queue) / MAX_QUEUE, 0, 1))
        obs[65] = float(np.clip(
            (self._carbon_intensity(self._step) - 50) / 850, 0, 1
        ))
        obs[66] = float(self._step / self.max_steps)
        return obs

    # ── gymnasium API ─────────────────────────────────────────────────────────

    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed)
        if seed is not None:
            self._rng = np.random.default_rng(seed)
        elif self._base_seed is not None:
            self._rng = np.random.default_rng(self._base_seed)
        else:
            self._rng = np.random.default_rng()

        self._reset_state()

        task = self._spawn_task()
        if task:
            self._queue.append(task)

        return self._build_obs(), self._build_info()

    def step(self, action: int):
        assert self.action_space.contains(action)

        assignment_penalty = 0.0
        if self._queue:
            head_task = self._queue[0]
            if action < N_SERVERS:
                if self._can_fit(action, head_task):
                    self._assign_task(head_task, action)
                    self._queue.pop(0)
                else:
                    assignment_penalty = 0.5

        step_sla_violations  = self._advance_tasks()
        step_sla_violations += self._expire_queued_tasks()

        ci             = self._carbon_intensity(self._step)
        total_power_kw = sum(self._server_power(i) for i in range(N_SERVERS)) / 1000.0
        energy_kwh     = total_power_kw * (1.0 / 60.0)
        co2_g          = energy_kwh * ci

        self._total_energy += energy_kwh
        self._total_co2    += co2_g

        norm_co2    = co2_g / 500.0
        norm_energy = energy_kwh / 0.15
        norm_sla    = float(step_sla_violations)

        reward = -(
            0.5  * norm_co2
            + 0.3  * norm_energy
            + 0.2  * norm_sla
            + 0.05 * assignment_penalty
        )
        self._total_sla += norm_sla

        new_task = self._spawn_task()
        if new_task and len(self._queue) < MAX_QUEUE:
            self._queue.append(new_task)

        self._step += 1
        terminated = False
        truncated  = self._step >= self.max_steps

        return self._build_obs(), reward, terminated, truncated, self._build_info(
            step_co2=co2_g, step_energy=energy_kwh, step_sla=step_sla_violations
        )

    # ── rendering ─────────────────────────────────────────────────────────────

    def render(self) -> str | None:
        lines = [
            f"╔══════════════════════════════════════════════════════╗",
            f"║  DataCenterEnv  step={self._step:>3}/{self.max_steps}  "
            f"CI={self._carbon_intensity(self._step):>5.0f} gCO₂/kWh  ║",
            f"╠══════════════════════════════════════════════════════╣",
            f"  {'Type':<7} {'CPU%':>6} {'MEM%':>6} {'Power(W)':>9} {'Tasks':>6}",
            "  " + "─" * 44,
        ]
        for i, spec in enumerate(FLEET):
            cpu_p = 100 * self._cpu_used[i] / spec.cpu_capacity
            mem_p = 100 * self._mem_used[i] / spec.mem_capacity
            pwr   = self._server_power(i)
            n_t   = len(self._active_tasks[i])
            bar   = "█" * int(cpu_p / 10)
            lines.append(
                f"  {spec.name:<7} {cpu_p:>5.1f}% {mem_p:>5.1f}%"
                f" {pwr:>8.1f}W {n_t:>5}  {bar}"
            )
        lines += [
            f"╠══════════════════════════════════════════════════════╣",
            f"  Queue length  : {len(self._queue)}",
            f"  Completed     : {self._completed}",
            f"  SLA misses    : {self._missed_sla}",
            f"  Total CO₂     : {self._total_co2:.2f} g",
            f"  Total energy  : {self._total_energy*1000:.2f} Wh",
            f"  Data source   : {'CloudSim+Real Carbon' if DataCenterEnv._DATA_LOADED else 'Synthetic'}",
            f"╚══════════════════════════════════════════════════════╝",
        ]
        output = "\n".join(lines)
        if self.render_mode == "human":
            print(output)
        return output

    def _build_info(self, **kwargs) -> dict[str, Any]:
        return {
            "step":               self._step,
            "queue_length":       len(self._queue),
            "completed":          self._completed,
            "missed_sla":         self._missed_sla,
            "total_co2_g":        self._total_co2,
            "total_energy_wh":    self._total_energy * 1000,
            "carbon_intensity":   self._carbon_intensity(self._step),
            "using_real_data":    DataCenterEnv._DATA_LOADED,
            **kwargs,
        }

    def close(self):
        pass


# ──────────────────────────────────────────────────────────────────────────────
# Smoke test
# ──────────────────────────────────────────────────────────────────────────────

def _demo(n_episodes: int = 2, render_every: int = 50) -> None:
    env = DataCenterEnv(seed=42)
    env.render_mode = "human"

    for ep in range(n_episodes):
        obs, info = env.reset(seed=ep)
        ep_reward = 0.0
        done      = False

        while not done:
            action = env.action_space.sample()
            obs, reward, terminated, truncated, info = env.step(action)
            ep_reward += reward
            done = terminated or truncated
            if info["step"] % render_every == 0:
                env.render()

        print(
            f"\nEpisode {ep+1:>2} | return={ep_reward:>8.3f} | "
            f"completed={info['completed']:>4} | missed SLA={info['missed_sla']:>3} | "
            f"CO₂={info['total_co2_g']:>7.1f} g | "
            f"energy={info['total_energy_wh']:>7.1f} Wh | "
            f"real_data={info['using_real_data']}\n" + "─" * 72
        )
    env.close()


if __name__ == "__main__":
    _demo()